BEGIN;

TRUNCATE TABLE "users" CASCADE;
TRUNCATE TABLE "oauth" CASCADE;
TRUNCATE TABLE "teachers" CASCADE;
TRUNCATE TABLE "students" CASCADE;
TRUNCATE TABLE "classroom" CASCADE;
TRUNCATE TABLE "courses" CASCADE;
TRUNCATE TABLE "enrollment" CASCADE;
TRUNCATE TABLE "grade" CASCADE;
TRUNCATE TABLE "schedule" CASCADE;

COMMIT;